# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{errand}
  s.version = "0.7.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Lindsay Holmwood"]
  s.date = %q{2011-05-12}
  s.description = %q{Errand provides Ruby bindings for RRD functions (via librrd), and a concise DSL for interacting with RRDs.}
  s.email = %q{lindsay@holmwood.id.au}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".cvsignore",
    "AUTHORS",
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/errand.rb",
    "spec/errand_spec.rb",
    "spec/spec.opts",
    "test/test_rrdtool.rb"
  ]
  s.homepage = %q{http://auxesis.github.com/errand}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Ruby language binding for RRD tool version 1.2+}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_runtime_dependency(%q<rrd-ffi>, [">= 0"])
    else
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rrd-ffi>, [">= 0"])
    end
  else
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rrd-ffi>, [">= 0"])
  end
end

